#!/usr/bin/env python3
"""Workflow orchestrator — iterates all topics, runs scouts + curation, creates PRs/issues."""

import datetime as dt
import os
import shutil
import subprocess
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.topic_config import REPO_ROOT


def run_cmd(args, check=True, capture=False):
    """Run a subprocess command with logging."""
    print(f"  $ {' '.join(args)}")
    if capture:
        return subprocess.run(args, capture_output=True, text=True, check=check, cwd=REPO_ROOT)
    return subprocess.run(args, check=check, cwd=REPO_ROOT)


def clean_topic_temp_files(topic_id):
    """Remove temporary scout signal files for a topic."""
    t_dir = os.path.join(REPO_ROOT, "topics", topic_id)
    for fname in ("grok-signals.md", "arxiv-signals.md", "weekly-suggestions.md"):
        path = os.path.join(t_dir, fname)
        if os.path.exists(path):
            os.remove(path)


def reset_to_main():
    """Ensure we're on main with a clean working tree."""
    subprocess.run(["git", "checkout", "main"], check=False, cwd=REPO_ROOT)
    subprocess.run(["git", "checkout", "--", "."], check=False, cwd=REPO_ROOT)
    subprocess.run(["git", "clean", "-fd", "topics/"], check=False, cwd=REPO_ROOT)


def process_topic(topic, run_id, date_str):
    """Process a single topic: scout, curate, create PR or issue."""
    topic_id = topic["id"]
    topic_name = topic["name"]
    topic_dir = os.path.join("topics", topic_id)
    suggestions_dir = os.path.join(".github", "research-suggestions", topic_id)

    # Step 1: Grok scout
    print(f"[{topic_id}] Running Grok scout...")
    run_cmd(["python3", "scripts/grok_scout.py", "--topic-id", topic_id])

    # Step 2: arXiv scout
    print(f"[{topic_id}] Running arXiv scout...")
    run_cmd(["python3", "scripts/arxiv_scout.py", "--topic-id", topic_id])

    # Step 3: Claude curation
    print(f"[{topic_id}] Running Claude curation...")
    result = run_cmd(
        ["python3", "scripts/claude_curate.py", "--topic-id", topic_id],
        capture=True,
    )
    print(result.stdout)
    if not result.stdout.strip():
        print(f"[{topic_id}] Warning: claude_curate.py produced no output", file=sys.stderr)

    # Parse decision
    decision = "NONE"
    for line in result.stdout.splitlines():
        if line.startswith("RESULT:"):
            decision = line.split(":", 1)[1].strip()
            break

    os.makedirs(os.path.join(REPO_ROOT, suggestions_dir), exist_ok=True)

    if decision == "FOUND":
        suggestions_src = os.path.join(REPO_ROOT, topic_dir, "weekly-suggestions.md")
        suggestions_dst = os.path.join(REPO_ROOT, suggestions_dir, f"{date_str}.md")

        # Create branch from main first, then write files to avoid orphaning on main
        branch = f"automation/weekly-{topic_id}-{run_id}"
        run_cmd(["git", "checkout", "-b", branch])

        if os.path.exists(suggestions_src):
            with open(suggestions_src) as sf:
                content = sf.read()
            log_content = "\n".join(content.splitlines()[1:])
            with open(suggestions_dst, "w") as df:
                df.write(log_content)

        suggestions_dst_rel = os.path.relpath(suggestions_dst, REPO_ROOT)
        run_cmd(["git", "add", f"{topic_dir}/README.md", suggestions_dst_rel])
        run_cmd([
            "git", "commit", "-m",
            f"chore: weekly resource suggestions for {topic_id} ({date_str})",
        ])
        run_cmd(["git", "push", "-u", "origin", branch])

        run_cmd([
            "gh", "pr", "create",
            "--title", f"chore: weekly resource suggestions for {topic_id} ({date_str})",
            "--body", (
                f"This draft PR was generated by the Research Assistant Agent for **{topic_name}**.\n\n"
                f"Review the suggestion log at `.github/research-suggestions/{topic_id}/{date_str}.md`."
            ),
            "--draft",
            "--label", "automation,research",
        ])

        # Return to main and reset working tree for next topic
        reset_to_main()

    else:
        # Create issue with scout outputs
        grok_path = os.path.join(REPO_ROOT, topic_dir, "grok-signals.md")
        arxiv_path = os.path.join(REPO_ROOT, topic_dir, "arxiv-signals.md")
        suggestions_path = os.path.join(REPO_ROOT, topic_dir, "weekly-suggestions.md")

        body_parts = [f"# Weekly research log ({topic_name}) — {date_str}\n"]
        body_parts.append("No high-confidence additions this week.\n")

        for label, path in [
            ("Claude decision", suggestions_path),
            ("Grok scout output", grok_path),
            ("arXiv scout output", arxiv_path),
        ]:
            body_parts.append(f"\n## {label}\n")
            if os.path.exists(path):
                with open(path) as pf:
                    body_parts.append(pf.read())
            else:
                body_parts.append("(not available)")

        issue_body = "\n".join(body_parts)
        run_cmd([
            "gh", "issue", "create",
            "--title", f"research assistant log ({topic_id}) (no PR) ({date_str})",
            "--body", issue_body,
            "--label", "automation,research,no-pr",
        ])

    # Clean up temp files
    clean_topic_temp_files(topic_id)

    return decision


def main():
    with open(os.path.join(REPO_ROOT, "topics.yml"), encoding="utf-8") as f:
        topics = yaml.safe_load(f).get("topics", [])

    if not topics:
        print("No topics configured in topics.yml")
        sys.exit(0)

    run_id = os.environ.get("GITHUB_RUN_ID", "local")
    date_str = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    errors = []

    for topic in topics:
        topic_id = topic["id"]
        topic_name = topic["name"]
        print(f"\n{'='*60}")
        print(f"Processing topic: {topic_name} ({topic_id})")
        print(f"{'='*60}\n")

        try:
            decision = process_topic(topic, run_id, date_str)
            print(f"[{topic_id}] Done: RESULT: {decision}")
        except Exception as exc:
            errors.append((topic_id, str(exc)))
            print(f"[{topic_id}] ERROR: {exc}", file=sys.stderr)
            # Print captured stderr if available (e.g. from CalledProcessError)
            if hasattr(exc, "stderr") and exc.stderr:
                print(f"[{topic_id}] STDERR:\n{exc.stderr}", file=sys.stderr)
            reset_to_main()
            clean_topic_temp_files(topic_id)
            continue

    # Summary
    print(f"\n{'='*60}")
    print(f"Processed {len(topics)} topic(s)")
    if errors:
        print(f"Errors in {len(errors)} topic(s):")
        for tid, err in errors:
            print(f"  - {tid}: {err}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
